twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_4_layout.html.twig']
=======
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

>>>>>>> 579663ce875f0d7d6c4ca38120bd4cfe3d00efca
